CREATE TABLE `users` ( 
	`id` INT NOT NULL AUTO_INCREMENT, 
	`username` VARCHAR(100) NOT NULL, 
	`email` VARCHAR(75) NOT NULL, 
	`password` VARCHAR(255) NOT NULL,
	`role` VARCHAR(20) NOT NULL,
	 PRIMARY KEY (`id`)
) ENGINE = InnoDB;